export default [
	{
		id : 1,
		title: "Happy Hour Fun",
		organizer : "Dewayne",
		purpose : "Networking",
		restaurant : "Water Grill",
		address : "123 2nd St, Los Angeles, CA 90001",
		date : "01/14/2020",
		time : "05:30PM",
		description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed leo non lacus commodo semper. Nam finibus quam ut urna porttitor tempor eu sed metus.",
		singlesOnly : "No",
		attendees : 4
	},
	{
		id : 2,
		title: "Single Mingle",
		organizer : "David",
		purpose : "Singles Night",
		restaurant : "Sonora Town",
		address : "321 4th St, Los Angeles, CA 90003",
		date : "02/14/2020",
		time : "07:00PM",
		description : "Praesent ut tellus quis quam accumsan gravida id viverra leo. Phasellus congue malesuada arcu, blandit malesuada augue mollis id. Nulla dictum lectus quis massa pulvinar luctus. Ut vel lobortis justo, id sagittis lacus. Vestibulum ut interdum dolor. Suspendisse bibendum condimentum mi at faucibus. Morbi eu mauris accumsan, rhoncus dui vitae, blandit leo.",
		singlesOnly : "Yes",
		attendees : 10
	},
	{
		id : 3,
		title: "Social Ramen",
		organizer : "Rick",
		purpose : "Social",
		restaurant : "Daikokuya",
		address : "30923 Union Ave, Los Angeles, CA 90301",
		date : "03/02/2020",
		time : "07:45PM",
		description : "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque blandit eros in enim efficitur pharetra. Sed sit amet tellus sed libero malesuada tempor nec in ligula. Morbi hendrerit metus justo, id mattis sapien semper sed. Duis blandit tempus semper. Morbi vel metus tortor. Pellentesque ultrices lobortis ante.",
		singlesOnly : "No",
		attendees : 6
	},
	{
		id : 4,
		title: "Board Game Bananza",
		organizer : "David",
		purpose : "Game Night",
		restaurant : "Button Mash",
		address : "1391 Sunset Blvd., Los Angeles, CA 90026",
		date : "01/14/2020",
		time : "06:30PM",
		description : "In tincidunt a risus ut mattis. Sed justo eros, laoreet eu risus id, luctus auctor ipsum. Aenean vestibulum tellus vitae est viverra mattis. Phasellus id hendrerit risus, sit amet lobortis tellus. Proin tristique et mauris a imperdiet.",
		singlesOnly : "No",
		attendees : 25
	},
	{
		id : 5,
		title: "Tapas Anyone?",
		organizer : "Rick",
		purpose : "Social",
		restaurant : "Scum and Villainy Cantina",
		address : "6377 Hollywood Blvd., Los Angeles, CA 90028",
		date : "05/04/2020",
		time : "06:45PM",
		description : "In felis mi, efficitur at porttitor ac, egestas quis quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed eu nunc nec lorem malesuada ornare. Maecenas malesuada pellentesque risus, et egestas eros euismod eu.",
		singlesOnly : "No",
		attendees : 20
	},
	{
		id : 6,
		title: "French Cuisine with Wine",
		organizer : "Dewayne",
		purpose : "Social",
		restaurant : "Republique",
		address : "624 S La Brea Ave Hancock Park",
		date : "07/04/2020",
		time : "06:45PM",
		description : "French eatery with some of the best, fresh-baked pastries in Los Angeles! Join us for some delicious food, ice breakers and much more.",
		singlesOnly : "No",
		attendees : 13
	},
	{
		id : 7,
		title: "Central America Transport",
		organizer : "Venetta",
		purpose : "Networking",
		restaurant : "Running Goose",
		address : "1620 N Cahuenga Blvd Los Angeles, CA 90028",
		date : "10/04/2020",
		time : "06:45PM",
		description : "Inspired by the widely undiscovered specialties of Central America and the Yucatan, the Goose is a celebration of southern California's hidden pockets of cultural influence.",
		singlesOnly : "No",
		attendees : 10
	},
	{
		id : 8,
		title: "Bring your Business Cards",
		organizer : "Reynalda",
		purpose : "Networking",
		restaurant : "JOEY DTLA",
		address : "700 W 7th St, Los Angeles, CA 90017",
		date : "02/04/2020",
		time : "06:45PM",
		description : "Genuine Warmth & Care are always on the table",
		singlesOnly : "No",
		attendees : 6
	}
]
