export default [
	{
		id : 1,
		fname : "Rick",
		lname : "Mcqueeney",
		email : "rmcqueeney@gmail.com",
		password : "password1",
		dob : "03/02/1979",
		gender : "Male",
		occupation : "Marketing",
		status : "Married",
		summary : "Nam ullamcorper finibus purus, id facilisis nisi scelerisque in. Aliquam vel nisi id tellus efficitur sagittis. Sed vel maximus erat. Nunc dapibus purus massa, in molestie ipsum gravida vel. Phasellus varius nec risus a ornare.",
		events : [5, 3]
	},
	{
		id : 2,
		fname : "Reynalda",
		lname : "Goodman",
		email : "rgoodman@yahoo.com",
		password : "password2",
		dob : "11/14/1980",
		gender : "Female",
		occupation : "Lawyer",
		status : "Single",
		summary : "Vivamus vestibulum justo vel ultrices vehicula. Vivamus vitae maximus justo. Sed eu leo eu sem auctor suscipit et non ex.",
		events : [8]
	},
	{
		id : 3,
		fname : "Casey",
		lname : "Pilkenton",
		email : "cpilkenton@aol.com",
		password : "password3",
		dob : "04/24/1993",
		gender : "Male",
		occupation : "Engineer",
		status : "Separated",
		summary : "Sed nec scelerisque massa, aliquam facilisis dolor. Ut ante arcu, facilisis vitae malesuada nec, auctor eu nunc. Sed congue, mauris interdum vulputate tempor, est felis molestie nisl, id congue dui augue eu augue.",
		events : []
	},
	{
		id : 4,
		fname : "Venetta",
		lname : "Dossey",
		email : "vdossey@live.com",
		password : "password4",
		dob : "05/02/1965",
		gender : "Female",
		occupation : "Owner",
		status : "Single",
		summary : "Donec id tellus nunc. Aliquam erat volutpat. Nam a elit maximus, cursus metus et, sollicitudin augue.",
		events : [7]
	},
	{
		id : 5,
		fname : "David",
		lname : "Bradley",
		email : "dbradley@msn.com",
		password : "password5",
		dob : "10/31/1983",
		gender : "Male",
		occupation : "Full Stack Developer",
		status : "Single",
		summary : "Maecenas eleifend ante eu arcu lacinia blandit. Donec ante mauris, dignissim id ligula vel, feugiat pharetra lectus. In eget turpis sed mi malesuada auctor vitae quis elit.",
		events : [2,4]
	},
	{
		id : 6,
		fname : "Dewayne",
		lname : "Piper",
		email : "dpiper@gmail.com",
		password : "password6",
		dob : "02/24/1990",
		gender : "Male",
		occupation : "Chef",
		status : "Married",
		summary : "Suspendisse tempor eget purus vel feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo sapien eget dui interdum venenatis.",
		events : [1, 6]
	}
]